import React, { useState, useEffect, useRef, useMemo } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {
  Layers,
  MapPin,
  Navigation,
  Clock,
  Coins,
  CheckCircle2,
  Sparkles,
  Store,
  User,
  Phone,
  ArrowRight,
  TrendingUp,
  AlertCircle,
  Sliders,
  ChevronRight,
  Camera,
  DollarSign,
  Maximize2,
  Minimize2,
  X,
  Compass,
  FileCheck,
  ShieldCheck,
  Fuel,
  Car,
  Gauge,
  Activity,
  RefreshCw,
} from 'lucide-react';
import {
  BatchDeliveryGroup,
  BatchEngineConfig,
  BatchRouteStop,
  BatchStopStatus,
  TrafficConditionLevel,
  TrafficOffsetConfig,
  StopCumulativeETA,
  BatchCumulativeETAResult,
} from '../types';
import {
  advanceBatchRouteStop,
  DEFAULT_BATCH_CONFIG,
  getBatchRouteCoordinates,
  groupOrdersIntoBatches,
  MILA_CANDIDATE_ORDERS_POOL,
  calculateCumulativeBatchETA,
  MILA_TRAFFIC_CONDITIONS,
} from '../services/courierBatchDeliveryService';

interface Props {
  initialBatch?: BatchDeliveryGroup | null;
  onClose?: () => void;
  onBatchCompleted?: (batch: BatchDeliveryGroup) => void;
  onEarningsUpdated?: (amountDZD: number) => void;
}

export const CourierBatchRouteView: React.FC<Props> = ({
  initialBatch,
  onClose,
  onBatchCompleted,
  onEarningsUpdated,
}) => {
  // Engine Configuration State
  const [config, setConfig] = useState<BatchEngineConfig>(DEFAULT_BATCH_CONFIG);
  const [isConfigOpen, setIsConfigOpen] = useState(false);

  // Batches list generated by the Batch Engine
  const [availableBatches, setAvailableBatches] = useState<BatchDeliveryGroup[]>(() =>
    groupOrdersIntoBatches(MILA_CANDIDATE_ORDERS_POOL, DEFAULT_BATCH_CONFIG)
  );

  // Active Batch in progress
  const [activeBatch, setActiveBatch] = useState<BatchDeliveryGroup | null>(() => {
    if (initialBatch) return initialBatch;
    const batches = groupOrdersIntoBatches(MILA_CANDIDATE_ORDERS_POOL, DEFAULT_BATCH_CONFIG);
    return batches.length > 0 ? { ...batches[0], status: 'ACTIVE' } : null;
  });

  const [selectedStopDetail, setSelectedStopDetail] = useState<BatchRouteStop | null>(null);
  const [isMapExpanded, setIsMapExpanded] = useState(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  // Dynamic Real-time Traffic Offset & Cumulative ETA State
  const [trafficLevel, setTrafficLevel] = useState<TrafficConditionLevel>('MODERATE');
  const [isAutoTraffic, setIsAutoTraffic] = useState(true);
  const [currentTime, setCurrentTime] = useState<Date>(() => new Date());

  // Periodically refresh the reference clock so ETAs dynamically count down
  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentTime(new Date());
    }, 12000);
    return () => clearInterval(timer);
  }, []);

  // Compute dynamic cumulative ETA adjusting for real-time traffic offsets
  const cumulativeETA: BatchCumulativeETAResult | null = useMemo(() => {
    if (!activeBatch) return null;
    return calculateCumulativeBatchETA(activeBatch, [36.4528, 6.2675], trafficLevel, currentTime);
  }, [activeBatch, trafficLevel, currentTime]);

  const handleTrafficChange = (level: TrafficConditionLevel) => {
    setTrafficLevel(level);
    const config = MILA_TRAFFIC_CONDITIONS[level];
    setToastMessage(`🚦 Condition Trafic Ahmed Rachedi mise à jour : ${config.label} (${config.description})`);
    setTimeout(() => setToastMessage(null), 3500);
  };

  // Leaflet Map Refs
  const mapContainerRef = useRef<HTMLDivElement>(null);
  const mapInstanceRef = useRef<L.Map | null>(null);
  const markersRef = useRef<L.Marker[]>([]);
  const polylineRef = useRef<L.Polyline | null>(null);

  // Re-run the batch grouping engine when config sliders change
  const handleConfigChange = (newConfig: Partial<BatchEngineConfig>) => {
    const updated = { ...config, ...newConfig };
    setConfig(updated);
    const newBatches = groupOrdersIntoBatches(MILA_CANDIDATE_ORDERS_POOL, updated);
    setAvailableBatches(newBatches);
    setToastMessage(`⚡ Moteur de groupage actualisé : ${newBatches.length} tournées optimisées trouvées`);
    setTimeout(() => setToastMessage(null), 3000);
  };

  const handleSelectBatch = (batch: BatchDeliveryGroup) => {
    setActiveBatch({ ...batch, status: 'ACTIVE' });
    setToastMessage(`🚀 Tournée ${batch.batchCode} activée (${batch.stops.length} arrêts) !`);
    setTimeout(() => setToastMessage(null), 3000);
  };

  const handleAdvanceCurrentStop = () => {
    if (!activeBatch) return;
    const currentStop = activeBatch.stops[activeBatch.currentStopIndex];
    if (!currentStop) return;

    const nextBatch = advanceBatchRouteStop(activeBatch);
    setActiveBatch(nextBatch);

    if (currentStop.type === 'DROPOFF') {
      const payout = Math.round(activeBatch.totalCourierPayoutDZD / activeBatch.orders.length);
      onEarningsUpdated?.(payout);
      setToastMessage(`✓ Arrêt #${currentStop.stopNumber} terminé ! ${currentStop.cashToCollectDZD} DZD perçus.`);
    } else {
      setToastMessage(`✓ Arrêt #${currentStop.stopNumber} validé : Colis récupéré chez ${currentStop.targetName}`);
    }

    if (nextBatch.status === 'COMPLETED') {
      onBatchCompleted?.(nextBatch);
      onEarningsUpdated?.(activeBatch.batchBonusDZD); // Grant batch bonus!
      setToastMessage(`🎉 Tournée groupée ${nextBatch.batchCode} terminée avec succès ! Bonus +${nextBatch.batchBonusDZD} DZD crédité.`);
    }

    setTimeout(() => setToastMessage(null), 4000);
  };

  // --- INITIALIZE & UPDATE LEAFLET MAP ---
  useEffect(() => {
    if (!mapContainerRef.current) return;

    if (!mapInstanceRef.current) {
      const map = L.map(mapContainerRef.current, {
        center: [36.39308, 6.13022],
        zoom: 15,
        minZoom: 13,
        maxZoom: 18,
        maxBounds: [
          [36.375, 6.105],
          [36.415, 6.155],
        ],
        maxBoundsViscosity: 1.0,
        zoomControl: false,
        attributionControl: false,
      });

      L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png', {
        maxZoom: 19,
      }).addTo(map);

      mapInstanceRef.current = map;
    }

    const map = mapInstanceRef.current;

    // Clear old markers & lines
    markersRef.current.forEach((m) => m.remove());
    markersRef.current = [];
    if (polylineRef.current) {
      polylineRef.current.remove();
      polylineRef.current = null;
    }

    if (!activeBatch) return;

    const coordinates = getBatchRouteCoordinates(activeBatch);

    // Draw multi-stop polyline
    const routePolyline = L.polyline(coordinates, {
      color: '#00B578',
      weight: 5,
      opacity: 0.9,
      dashArray: '8, 6',
      lineCap: 'round',
    }).addTo(map);
    polylineRef.current = routePolyline;

    // Start / Courier Origin Marker
    const courierIcon = L.divIcon({
      className: 'custom-courier-marker',
      html: `
        <div style="background-color: #071E26; color: #D9943B; border: 2px solid #D9943B; width: 34px; height: 34px; border-radius: 50%; display: flex; align-items: center; justify-content: center; box-shadow: 0 4px 10px rgba(0,0,0,0.5); font-weight: 900; font-size: 16px;">
          🛵
        </div>
      `,
      iconSize: [34, 34],
      iconAnchor: [17, 17],
    });

    const courierMarker = L.marker(coordinates[0], { icon: courierIcon })
      .addTo(map)
      .bindPopup('<b>Position Coursier : Walid M.</b><br/>Départ de la tournée groupée');
    markersRef.current.push(courierMarker);

    // Numbered Multi-Stop Markers
    activeBatch.stops.forEach((stop, index) => {
      const isCurrent = index === activeBatch.currentStopIndex;
      const isCompleted = stop.status === 'COMPLETED';
      const isPickup = stop.type === 'PICKUP';

      let bgColor = isPickup ? '#D9943B' : '#00B578';
      let textColor = isPickup ? '#071E26' : '#ffffff';
      let border = isCurrent ? '3px solid #ffffff' : '2px solid rgba(255,255,255,0.8)';
      let pulseAnim = isCurrent ? 'animation: pulse 1.5s infinite;' : '';

      if (isCompleted) {
        bgColor = '#4B5563';
        textColor = '#9CA3AF';
        border = '1px solid #6B7280';
      }

      const stopIcon = L.divIcon({
        className: 'custom-stop-marker',
        html: `
          <div style="background-color: ${bgColor}; color: ${textColor}; border: ${border}; width: 32px; height: 32px; border-radius: 50%; display: flex; flex-direction: column; align-items: center; justify-content: center; box-shadow: 0 4px 12px rgba(0,0,0,0.4); font-weight: 800; font-size: 12px; ${pulseAnim}">
            <span>${isCompleted ? '✓' : stop.stopNumber}</span>
          </div>
        `,
        iconSize: [32, 32],
        iconAnchor: [16, 16],
      });

      const marker = L.marker([stop.lat, stop.lng], { icon: stopIcon })
        .addTo(map)
        .bindPopup(`
          <div style="font-family: system-ui, sans-serif; font-size: 12px; color: #111;">
            <b>Arrêt #${stop.stopNumber} : ${stop.roleLabel}</b><br/>
            <strong>${stop.targetName}</strong><br/>
            <span>${stop.address}</span><br/>
            ${stop.cashToCollectDZD > 0 ? `<b style="color: #00875A;">À encaisser: ${stop.cashToCollectDZD} DZD</b>` : ''}
          </div>
        `);

      marker.on('click', () => {
        setSelectedStopDetail(stop);
      });

      markersRef.current.push(marker);
    });

    // Fit map bounds to encompass all stops
    if (coordinates.length > 1) {
      map.fitBounds(routePolyline.getBounds(), { padding: [40, 40] });
    }
  }, [activeBatch, isMapExpanded]);

  const currentStop = activeBatch ? activeBatch.stops[activeBatch.currentStopIndex] : null;
  const currentStopETA = cumulativeETA?.stopsETA.find((s) => s.stopId === currentStop?.id);

  return (
    <div className="bg-[#141619] min-h-screen text-white flex flex-col font-sans pb-16">
      {/* Top Bar Header */}
      <header className="bg-[#1C1E23] border-b border-white/10 px-4 py-3 sticky top-0 z-30 shadow-md">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-[#D9943B] text-[#071E26] flex items-center justify-center font-black shadow-md">
              <Layers size={18} />
            </div>
            <div>
              <div className="flex items-center gap-1.5">
                <h1 className="font-extrabold text-sm text-white">
                  <span className="sm:hidden">Tournées</span>
                  <span className="hidden sm:inline">Moteur de Tournées Groupées</span>
                </h1>
                <span className="bg-amber-400/20 text-amber-300 text-[10px] font-bold px-1.5 py-0.2 rounded">
                  Batch Engine Rachedi
                </span>
              </div>
              <p className="text-[11px] text-zinc-400">
                Regroupement par rayon & synchronisation cuisines
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setIsConfigOpen(!isConfigOpen)}
              className="px-2.5 py-1.5 rounded-xl bg-white/10 hover:bg-white/15 text-zinc-200 text-xs font-bold flex items-center gap-1.5 transition-colors cursor-pointer"
              title="Ajuster les critères de groupage"
            >
              <Sliders size={13} className="text-[#D9943B]" />
              <span className="hidden sm:inline">Paramètres</span>
            </button>

            {onClose && (
              <button
                onClick={onClose}
                className="w-8 h-8 rounded-xl bg-white/10 hover:bg-white/20 text-zinc-300 hover:text-white flex items-center justify-center transition-colors cursor-pointer"
                title="Fermer"
              >
                <X size={16} />
              </button>
            )}
          </div>
        </div>

        {/* Engine Filter & Radius Tuning Panel (Collapsible) */}
        {isConfigOpen && (
          <div className="mt-3 pt-3 border-t border-white/10 space-y-3 text-xs bg-black/20 p-3 rounded-2xl animate-in fade-in slide-in-from-top duration-200">
            <div className="flex items-center justify-between">
              <span className="font-bold text-amber-300 flex items-center gap-1.5">
                <Sparkles size={14} />
                <span>Paramètres de l'Algorithme de Corridor Ahmed Rachedi</span>
              </span>
              <span className="text-[10px] text-zinc-400">Mise à jour en temps réel</span>
            </div>

            {/* Slider 1: Destination Radius */}
            <div className="space-y-1">
              <div className="flex justify-between text-[11px]">
                <span className="text-zinc-300">Rayon max entre adresses clients :</span>
                <span className="font-mono font-bold text-emerald-400">{config.maxDestinationRadiusMeters} mètres</span>
              </div>
              <input
                type="range"
                min="200"
                max="1200"
                step="50"
                value={config.maxDestinationRadiusMeters}
                onChange={(e) => handleConfigChange({ maxDestinationRadiusMeters: Number(e.target.value) })}
                className="w-full accent-[#00B578] cursor-pointer"
              />
              <div className="flex justify-between text-[9px] text-zinc-500">
                <span>200m (Même immeuble)</span>
                <span>600m (Même quartier)</span>
                <span>1.2km (Périmètre étendu)</span>
              </div>
            </div>

            {/* Slider 2: Kitchen Ready Time Window */}
            <div className="space-y-1">
              <div className="flex justify-between text-[11px]">
                <span className="text-zinc-300">Écart max de préparation cuisine :</span>
                <span className="font-mono font-bold text-amber-400">±{config.maxReadyTimeDiffMinutes} minutes</span>
              </div>
              <input
                type="range"
                min="3"
                max="25"
                step="1"
                value={config.maxReadyTimeDiffMinutes}
                onChange={(e) => handleConfigChange({ maxReadyTimeDiffMinutes: Number(e.target.value) })}
                className="w-full accent-[#D9943B] cursor-pointer"
              />
              <div className="flex justify-between text-[9px] text-zinc-500">
                <span>±3 min (Prêts simultanés)</span>
                <span>±10 min (Standard chaud)</span>
                <span>±25 min (Tolérance large)</span>
              </div>
            </div>

            {/* Selector: Max Orders per Batch */}
            <div className="flex items-center justify-between pt-1">
              <span className="text-zinc-300">Capacité du caisson isotherme :</span>
              <div className="flex gap-1.5">
                {[2, 3].map((num) => (
                  <button
                    key={num}
                    onClick={() => handleConfigChange({ maxOrdersPerBatch: num })}
                    className={`px-3 py-1 rounded-lg font-bold text-xs transition-colors cursor-pointer ${
                      config.maxOrdersPerBatch === num
                        ? 'bg-[#D9943B] text-[#071E26] font-black'
                        : 'bg-white/10 text-zinc-300 hover:bg-white/15'
                    }`}
                  >
                    {num} commandes max
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}
      </header>

      {/* Main Content Area */}
      <main className="p-3.5 space-y-3.5 flex-1 max-w-xl mx-auto w-full">
        {/* BATCH SELECTOR (IF MULTIPLE BATCHES DETECTED) */}
        {availableBatches.length > 1 && (
          <div className="space-y-2">
            <span className="text-[11px] font-bold text-zinc-400 uppercase tracking-wide flex items-center gap-1.5">
              <Sparkles size={13} className="text-[#D9943B]" />
              <span>{availableBatches.length} Tournées Groupées Proposées par l'Algorithme :</span>
            </span>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {availableBatches.map((batch) => {
                const isSelected = activeBatch?.id === batch.id;
                return (
                  <button
                    key={batch.id}
                    onClick={() => handleSelectBatch(batch)}
                    className={`text-left p-3 rounded-2xl border transition-all cursor-pointer ${
                      isSelected
                        ? 'bg-gradient-to-br from-[#D9943B]/20 to-emerald-500/20 border-[#D9943B] shadow-md'
                        : 'bg-[#1C1E23] border-white/10 hover:border-white/20'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-extrabold text-xs text-white flex items-center gap-1">
                        <span>{batch.batchCode}</span>
                        <span className="text-[9px] bg-emerald-500/20 text-emerald-400 px-1.5 py-0.2 rounded">
                          {batch.synergyScorePercent}% Synergie
                        </span>
                      </span>
                      <span className="text-emerald-400 font-extrabold text-xs">
                        +{batch.totalCourierPayoutDZD} DZD
                      </span>
                    </div>

                    <div className="text-[11px] text-zinc-300 mt-1 font-semibold truncate">
                      📍 {batch.neighborhood}
                    </div>

                    <div className="flex items-center justify-between text-[10px] text-zinc-400 mt-2 pt-2 border-t border-white/5">
                      <span>{batch.stops.length} arrêts • ~{batch.totalDurationMinutes} min</span>
                      <span className="text-amber-300 font-bold">+{batch.batchBonusDZD} DZD Bonus</span>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {/* ACTIVE BATCH PERFORMANCE BANNER */}
        {activeBatch && (
          <div className="bg-gradient-to-r from-[#1E232A] via-[#1A1D22] to-[#16181C] border border-amber-400/40 rounded-2xl p-3.5 shadow-xl space-y-3">
            <div className="flex items-start justify-between">
              <div>
                <div className="flex items-center gap-1.5">
                  <span className="bg-[#D9943B] text-[#071E26] text-[10px] font-black px-2 py-0.5 rounded-full uppercase tracking-wider">
                    Tournée {activeBatch.batchCode}
                  </span>
                  <span className="bg-emerald-500/20 text-emerald-400 border border-emerald-500/40 text-[10px] font-bold px-2 py-0.5 rounded-full">
                    Synergie {activeBatch.synergyScorePercent}%
                  </span>
                  {activeBatch.status === 'COMPLETED' && (
                    <span className="bg-blue-500/20 text-blue-400 text-[10px] font-bold px-2 py-0.5 rounded-full">
                      Terminée ✓
                    </span>
                  )}
                </div>

                <h3 className="font-extrabold text-sm text-white mt-1">
                  Corridor {activeBatch.neighborhood}
                </h3>
              </div>

              <div className="text-right">
                <span className="text-xs text-zinc-400 font-semibold block">Gain Coursier Total</span>
                <span className="text-lg font-black text-[#00B578]">
                  +{activeBatch.totalCourierPayoutDZD} DZD
                </span>
                <span className="text-[9px] text-amber-300 block font-bold">
                  (inclut +{activeBatch.batchBonusDZD} DZD prime groupage)
                </span>
              </div>
            </div>

            {/* Quick Multi-Metric Strip */}
            <div className="grid grid-cols-3 gap-2 pt-2 border-t border-white/10 text-center text-xs">
              <div className="bg-white/5 rounded-xl py-1.5 px-1">
                <span className="text-zinc-400 text-[9px] block">Rayon entre clients</span>
                <span className="font-bold text-white text-xs">
                  {activeBatch.maxRadiusBetweenDropoffsMeters} mètres
                </span>
              </div>
              <div className="bg-white/5 rounded-xl py-1.5 px-1">
                <span className="text-zinc-400 text-[9px] block">Écart prépa cuisine</span>
                <span className="font-bold text-amber-400 text-xs">
                  {activeBatch.readyTimeSpreadMinutes} min écart
                </span>
              </div>
              <div className="bg-white/5 rounded-xl py-1.5 px-1">
                <span className="text-zinc-400 text-[9px] block">Économie de trajet</span>
                <span className="font-bold text-emerald-400 text-xs">
                  -{Math.round(activeBatch.distanceSavedMeters / 100) / 10} km
                </span>
              </div>
            </div>

            {/* Green / Eco Impact Strip */}
            <div className="flex items-center justify-between text-[10px] bg-emerald-500/10 border border-emerald-500/20 px-2.5 py-1.5 rounded-xl text-emerald-300">
              <span className="flex items-center gap-1">
                <Fuel size={12} />
                <span>Gain scooter : ~{activeBatch.timeSavedMinutes} min économisées</span>
              </span>
              <span>🌿 -{activeBatch.co2SavedGrams}g CO2 évités</span>
            </div>
          </div>
        )}

        {/* DYNAMIC CUMULATIVE ETA & REAL-TIME TRAFFIC OFFSET DASHBOARD */}
        {activeBatch && cumulativeETA && (
          <div className="bg-[#1C1E23] border border-white/10 rounded-2xl p-4 shadow-xl space-y-3.5 animate-in fade-in">
            {/* Header with live telemetry status */}
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="relative flex h-2.5 w-2.5">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-[#00B578] opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-[#00B578]"></span>
                </span>
                <div>
                  <h3 className="font-extrabold text-xs text-white uppercase tracking-wider flex items-center gap-1.5">
                    <Activity size={13} className="text-[#D9943B]" />
                    <span>Calculateur d'ETA Dynamique & Trafic en Direct</span>
                  </h3>
                  <span className="text-[10px] text-zinc-400">
                    Ahmed Rachedi • Actualisé à {cumulativeETA.calculatedAt}
                  </span>
                </div>
              </div>

              <span className={`text-[10px] font-extrabold px-2 py-0.5 rounded-full border ${cumulativeETA.traffic.badgeColor}`}>
                {cumulativeETA.traffic.label}
              </span>
            </div>

            {/* 3 Core Cumulative Indicators */}
            <div className="grid grid-cols-3 gap-2 text-center">
              {/* Box 1: Cumulative Travel Time */}
              <div className="bg-gradient-to-br from-white/5 to-white/10 border border-white/10 rounded-xl p-2.5 flex flex-col justify-between">
                <div>
                  <span className="text-[10px] text-zinc-400 font-bold flex items-center justify-center gap-1">
                    <Clock size={11} className="text-[#D9943B]" />
                    <span>ETA Cumulé</span>
                  </span>
                  <div className="text-xl font-black text-white mt-0.5">
                    {cumulativeETA.totalCumulativeDurationMinutes} <span className="text-xs font-bold text-zinc-400">min</span>
                  </div>
                </div>
                <div className="mt-1 pt-1 border-t border-white/10">
                  <span className="text-[9px] font-mono font-bold text-emerald-400 block">
                    🏁 Arrivée {cumulativeETA.finalDeliveryClock}
                  </span>
                </div>
              </div>

              {/* Box 2: Cumulative Distance */}
              <div className="bg-gradient-to-br from-white/5 to-white/10 border border-white/10 rounded-xl p-2.5 flex flex-col justify-between">
                <div>
                  <span className="text-[10px] text-zinc-400 font-bold flex items-center justify-center gap-1">
                    <Navigation size={11} className="text-emerald-400" />
                    <span>Distance Cumulée</span>
                  </span>
                  <div className="text-xl font-black text-white mt-0.5">
                    {(cumulativeETA.totalCumulativeDistanceMeters / 1000).toFixed(1)} <span className="text-xs font-bold text-zinc-400">km</span>
                  </div>
                </div>
                <div className="mt-1 pt-1 border-t border-white/10">
                  <span className="text-[9px] text-zinc-300 block font-medium">
                    {cumulativeETA.remainingStopsCount} arrêts restants
                  </span>
                </div>
              </div>

              {/* Box 3: Adjusted Speed */}
              <div className="bg-gradient-to-br from-white/5 to-white/10 border border-white/10 rounded-xl p-2.5 flex flex-col justify-between">
                <div>
                  <span className="text-[10px] text-zinc-400 font-bold flex items-center justify-center gap-1">
                    <Gauge size={11} className="text-amber-400" />
                    <span>Vitesse Corrigée</span>
                  </span>
                  <div className="text-xl font-black text-amber-300 mt-0.5">
                    {cumulativeETA.averageSpeedKmH} <span className="text-xs font-bold text-zinc-400">km/h</span>
                  </div>
                </div>
                <div className="mt-1 pt-1 border-t border-white/10">
                  <span className="text-[9px] text-zinc-400 block truncate">
                    Scooter urbain
                  </span>
                </div>
              </div>
            </div>

            {/* Decomposed Travel Time Stacked Bar */}
            <div className="space-y-1.5 bg-black/25 rounded-xl p-2.5 border border-white/5 text-xs">
              <div className="flex items-center justify-between text-[10px]">
                <span className="font-bold text-zinc-300 flex items-center gap-1">
                  <TrendingUp size={11} className="text-[#D9943B]" />
                  <span>Décomposition du temps de trajet cumulé :</span>
                </span>
                <span className="font-mono text-zinc-400">
                  {cumulativeETA.totalCumulativeDurationMinutes} min au total
                </span>
              </div>

              {/* Multi-Segment Color Bar */}
              <div className="h-2 rounded-full bg-zinc-800 flex overflow-hidden">
                <div
                  style={{
                    width: `${Math.max(10, Math.round((cumulativeETA.baseTransitMinutes / cumulativeETA.totalCumulativeDurationMinutes) * 100))}%`,
                  }}
                  className="bg-blue-500 transition-all duration-300"
                  title="Conduite pure de base"
                />
                <div
                  style={{
                    width: `${Math.max(5, Math.round((cumulativeETA.trafficOffsetMinutes / cumulativeETA.totalCumulativeDurationMinutes) * 100))}%`,
                  }}
                  className="bg-amber-400 transition-all duration-300"
                  title="Décalage trafic en direct"
                />
                <div
                  style={{
                    width: `${Math.max(10, Math.round((cumulativeETA.serviceBufferMinutes / cumulativeETA.totalCumulativeDurationMinutes) * 100))}%`,
                  }}
                  className="bg-emerald-500 transition-all duration-300"
                  title="Manutention & Remises"
                />
              </div>

              {/* Legend with exact numbers */}
              <div className="grid grid-cols-3 gap-1 pt-1 text-[9px] text-zinc-300">
                <div className="flex items-center gap-1">
                  <span className="w-2 h-2 rounded-full bg-blue-500 shrink-0"></span>
                  <span className="truncate">Route : <b>{cumulativeETA.baseTransitMinutes} min</b></span>
                </div>
                <div className="flex items-center gap-1 text-amber-300 font-medium">
                  <span className="w-2 h-2 rounded-full bg-amber-400 shrink-0"></span>
                  <span className="truncate">Trafic : <b>+{cumulativeETA.trafficOffsetMinutes} min</b></span>
                </div>
                <div className="flex items-center gap-1 text-emerald-400 font-medium">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 shrink-0"></span>
                  <span className="truncate">Remise : <b>+{cumulativeETA.serviceBufferMinutes} min</b></span>
                </div>
              </div>
            </div>

            {/* Real-time Traffic Offset Controls */}
            <div className="space-y-1.5 pt-1">
              <div className="flex items-center justify-between text-[11px]">
                <span className="font-bold text-zinc-300 flex items-center gap-1">
                  <Car size={12} className="text-[#D9943B]" />
                  <span>Ajustement Trafic (Ahmed Rachedi) :</span>
                </span>
                <span className="text-[9px] text-zinc-400">
                  Décalage instantané recalculé
                </span>
              </div>

              <div className="grid grid-cols-4 gap-1.5">
                {(['FLUID', 'MODERATE', 'HEAVY', 'CONGESTED'] as TrafficConditionLevel[]).map((lvl) => {
                  const item = MILA_TRAFFIC_CONDITIONS[lvl];
                  const isSelected = trafficLevel === lvl;
                  return (
                    <button
                      key={lvl}
                      type="button"
                      onClick={() => handleTrafficChange(lvl)}
                      className={`p-1.5 rounded-xl border text-center transition-all cursor-pointer ${
                        isSelected
                          ? 'bg-[#D9943B] text-[#071E26] border-[#D9943B] font-black shadow-md scale-[1.02]'
                          : 'bg-white/5 border-white/10 text-zinc-300 hover:bg-white/10 font-bold'
                      }`}
                    >
                      <div className="text-[10px] leading-tight truncate">{item.label.split(' ')[0]}</div>
                      <div className={`text-[8px] ${isSelected ? 'text-[#071E26] font-black' : 'text-zinc-400'}`}>
                        {lvl === 'FLUID' ? '0 min' : lvl === 'MODERATE' ? '+3 min' : lvl === 'HEAVY' ? '+7 min' : '+12 min'}
                      </div>
                    </button>
                  );
                })}
              </div>

              {/* Corridor Advisory Alert Box */}
              <div className="mt-1 flex items-start gap-1.5 text-[10px] text-zinc-400 bg-white/5 p-2 rounded-xl border border-white/5">
                <AlertCircle size={13} className="text-amber-400 shrink-0 mt-0.5" />
                <div>
                  <span className="text-zinc-200 font-semibold">{cumulativeETA.traffic.reportedCorridor} : </span>
                  <span>{cumulativeETA.traffic.description}</span>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* INTERACTIVE CONSOLIDATED MULTI-STOP LEAFLET MAP */}
        <div className="bg-[#1C1E23] border border-white/10 rounded-2xl overflow-hidden shadow-lg relative">
          <div className="px-3.5 py-2.5 bg-[#22252A] border-b border-white/10 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Compass size={16} className="text-[#D9943B] animate-spin-slow" />
              <span className="font-bold text-xs text-white">
                Carte du Tracé Multi-Arrêts Consolidé ({activeBatch?.stops.length || 0} étapes)
              </span>
            </div>

            <button
              onClick={() => setIsMapExpanded(!isMapExpanded)}
              className="w-7 h-7 rounded-lg bg-white/10 hover:bg-white/20 text-zinc-300 hover:text-white flex items-center justify-center transition-colors"
              title={isMapExpanded ? 'Réduire la carte' : 'Agrandir la carte'}
            >
              {isMapExpanded ? <Minimize2 size={14} /> : <Maximize2 size={14} />}
            </button>
          </div>

          <div
            ref={mapContainerRef}
            className={`w-full transition-all duration-300 ${
              isMapExpanded ? 'h-[380px]' : 'h-[220px]'
            }`}
          />

          {/* Map Legend Floating Overlay */}
          <div className="absolute bottom-2 left-2 right-2 bg-black/80 backdrop-blur-md rounded-xl p-2 border border-white/10 flex items-center justify-around text-[10px] font-bold z-[1000]">
            <span className="flex items-center gap-1 text-white">
              <span className="w-2.5 h-2.5 rounded-full bg-[#071E26] border border-[#D9943B] inline-block"></span>
              <span>Départ 🛵</span>
            </span>
            <span className="flex items-center gap-1 text-[#E5A34C]">
              <span className="w-2.5 h-2.5 rounded-full bg-[#D9943B] inline-block"></span>
              <span>Enlèvement Boutique</span>
            </span>
            <span className="flex items-center gap-1 text-emerald-400">
              <span className="w-2.5 h-2.5 rounded-full bg-[#00B578] inline-block"></span>
              <span>Livraison Client</span>
            </span>
          </div>
        </div>

        {/* CURRENT ACTIVE STOP ACTION CARD */}
        {activeBatch && currentStop && activeBatch.status !== 'COMPLETED' && (
          <div className="bg-gradient-to-br from-[#242830] to-[#1A1C20] border-2 border-emerald-400/70 rounded-2xl p-4 shadow-xl space-y-3.5 relative overflow-hidden animate-in fade-in">
            {/* Top Badge */}
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="w-7 h-7 rounded-full bg-emerald-500 text-white font-black text-xs flex items-center justify-center shadow-md">
                  {currentStop.stopNumber}
                </span>
                <div>
                  <span className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider block">
                    Arrêt Actuel ({currentStop.stopNumber} sur {activeBatch.stops.length})
                  </span>
                  <h4 className="font-black text-sm text-white">
                    {currentStop.roleLabel} • {currentStop.targetName}
                  </h4>
                </div>
              </div>

              <div className="text-right">
                <span className="text-[11px] font-bold text-emerald-300 bg-emerald-500/20 border border-emerald-500/30 px-2.5 py-1 rounded-full flex items-center gap-1 shadow-sm">
                  <Clock size={11} className="text-[#D9943B]" />
                  <span>{currentStopETA ? `Prévu ${currentStopETA.estimatedArrivalClock}` : `~${currentStop.estimatedArrivalMin} min`}</span>
                </span>
                {currentStopETA && (
                  <span className="text-[9px] text-zinc-400 block mt-0.5">
                    dans {currentStopETA.relativeMinutesFromNow} min (trafic +{Math.round(currentStopETA.trafficOffsetSeconds / 60)}m)
                  </span>
                )}
              </div>
            </div>

            {/* Target Address & Landmark */}
            <div className="bg-black/30 rounded-xl p-3 space-y-1 text-xs">
              <div className="flex items-start gap-2 text-zinc-200">
                <MapPin size={15} className="text-[#D9943B] shrink-0 mt-0.5" />
                <span className="font-semibold">{currentStop.address}</span>
              </div>
              {currentStop.landmark && (
                <p className="text-[11px] text-amber-300 pl-6">
                  ↳ Repère : {currentStop.landmark}
                </p>
              )}
              {currentStop.specialInstructions && (
                <p className="text-[10px] text-zinc-400 pl-6 italic">
                  Note : {currentStop.specialInstructions}
                </p>
              )}

              {/* Dynamic leg transit pill */}
              {currentStopETA && (
                <div className="pt-1.5 mt-1 border-t border-white/5 pl-6 flex items-center gap-2 text-[10px] text-zinc-400">
                  <span className="text-emerald-400 font-bold flex items-center gap-1">
                    <Navigation size={10} />
                    <span>~{currentStopETA.segmentDistanceMeters}m de trajet direct</span>
                  </span>
                  <span>•</span>
                  <span>Cumul : {(currentStopETA.cumulativeDistanceMeters / 1000).toFixed(2)} km</span>
                </div>
              )}
            </div>

            {/* Order Items Summary */}
            <div className="text-xs bg-white/5 p-2.5 rounded-xl flex items-center justify-between border border-white/5">
              <div className="truncate pr-2">
                <span className="text-[10px] text-zinc-400 block font-bold uppercase">
                  Colis ({currentStop.itemCount} articles)
                </span>
                <span className="text-zinc-200 font-medium text-xs truncate block">
                  {currentStop.itemsSummary}
                </span>
              </div>
              <span className="text-[10px] font-mono bg-white/10 px-2 py-1 rounded text-zinc-300 whitespace-nowrap">
                {currentStop.orderNumber}
              </span>
            </div>

            {/* Cash on Delivery prompt (if dropoff) */}
            {currentStop.cashToCollectDZD > 0 && (
              <div className="bg-amber-500/15 border border-amber-400/40 rounded-xl p-2.5 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <DollarSign size={18} className="text-[#D9943B]" />
                  <div>
                    <span className="text-xs font-bold text-white">À encaisser en espèces</span>
                    <span className="text-[10px] text-zinc-300 block">Remettre le ticket et la commande</span>
                  </div>
                </div>
                <span className="text-base font-black text-[#D9943B]">
                  {currentStop.cashToCollectDZD} DZD
                </span>
              </div>
            )}

            {/* Fast Action Buttons */}
            <div className="grid grid-cols-2 gap-2">
              <a
                href={`tel:${currentStop.phone}`}
                className="h-10 bg-white/10 hover:bg-white/15 active:scale-[0.98] text-white rounded-xl font-bold text-xs flex items-center justify-center gap-1.5 transition-all"
              >
                <Phone size={14} className="text-[#00B578]" />
                <span>Appeler {currentStop.type === 'PICKUP' ? 'Resto' : 'Client'}</span>
              </a>

              <button
                type="button"
                onClick={handleAdvanceCurrentStop}
                className="h-10 bg-[#00B578] hover:bg-emerald-600 active:scale-[0.98] text-white rounded-xl font-black text-xs flex items-center justify-center gap-1.5 shadow-lg transition-all cursor-pointer"
              >
                <CheckCircle2 size={15} />
                <span>
                  {currentStop.type === 'PICKUP'
                    ? 'Valider Enlèvement'
                    : `Valider Remise (${currentStop.cashToCollectDZD} DZD)`}
                </span>
              </button>
            </div>
          </div>
        )}

        {/* CONSOLIDATED STEP-BY-STEP MULTI-STOP TIMELINE */}
        {activeBatch && (
          <div className="bg-[#1C1E23] border border-white/10 rounded-2xl p-4 shadow-lg space-y-3">
            <div className="flex items-center justify-between pb-2 border-b border-white/10">
              <h4 className="text-xs font-bold text-white flex items-center gap-2">
                <Navigation size={15} className="text-[#D9943B]" />
                <span>Itinéraire Consolidé de la Tournée Groupée</span>
              </h4>
              <span className="text-[11px] text-zinc-400 font-mono">
                {activeBatch.stops.filter((s) => s.status === 'COMPLETED').length} / {activeBatch.stops.length} Terminés
              </span>
            </div>

            <div className="space-y-3 text-xs">
              {activeBatch.stops.map((stop, sIdx) => {
                const isCurrent = sIdx === activeBatch.currentStopIndex;
                const isCompleted = stop.status === 'COMPLETED';
                const isPickup = stop.type === 'PICKUP';
                const stopETA = cumulativeETA?.stopsETA[sIdx];

                return (
                  <div
                    key={stop.id}
                    onClick={() => setSelectedStopDetail(stop)}
                    className={`rounded-xl p-3 border transition-all cursor-pointer ${
                      isCurrent
                        ? 'bg-emerald-500/10 border-emerald-400 shadow-md ring-1 ring-emerald-400/40'
                        : isCompleted
                        ? 'bg-black/20 border-white/5 opacity-70'
                        : 'bg-[#24262B] border-white/5 hover:border-white/20'
                    }`}
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex items-start gap-2.5">
                        <div
                          className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-black shrink-0 mt-0.5 ${
                            isCompleted
                              ? 'bg-zinc-700 text-zinc-300'
                              : isPickup
                              ? 'bg-[#D9943B] text-[#071E26]'
                              : 'bg-[#00B578] text-white'
                          }`}
                        >
                          {isCompleted ? '✓' : stop.stopNumber}
                        </div>

                        <div>
                          <div className="flex items-center gap-1.5 flex-wrap">
                            <span className="font-extrabold text-white text-xs">
                              {stop.targetName}
                            </span>
                            <span
                              className={`text-[9px] font-bold px-1.5 py-0.2 rounded ${
                                isPickup
                                  ? 'bg-amber-400/20 text-amber-300'
                                  : 'bg-emerald-500/20 text-emerald-400'
                              }`}
                            >
                              {isPickup ? 'Enlèvement' : 'Livraison'}
                            </span>
                            {isCurrent && (
                              <span className="text-[9px] bg-emerald-500 text-zinc-950 font-black px-1.5 py-0.2 rounded animate-pulse">
                                EN COURS
                              </span>
                            )}
                          </div>

                          <p className="text-[11px] text-zinc-400 mt-0.5">
                            {stop.address}
                          </p>

                          {/* Dynamic Cumulative Distance & Segment Details */}
                          {stopETA && (
                            <div className="flex items-center gap-1.5 flex-wrap mt-1 text-[10px]">
                              <span className="bg-white/5 border border-white/5 px-1.5 py-0.2 rounded font-mono text-zinc-300 font-semibold">
                                Cumul : {(stopETA.cumulativeDistanceMeters / 1000).toFixed(2)} km
                              </span>
                              <span className="text-zinc-500">•</span>
                              <span className="text-zinc-400">↳ Étape : +{stopETA.segmentDistanceMeters}m</span>
                              {stopETA.trafficOffsetSeconds > 0 && !isCompleted && (
                                <>
                                  <span className="text-zinc-500">•</span>
                                  <span className="text-amber-400/90 font-medium">
                                    +{Math.round(stopETA.trafficOffsetSeconds / 60)} min trafic
                                  </span>
                                </>
                              )}
                            </div>
                          )}
                        </div>
                      </div>

                      <div className="text-right shrink-0">
                        {stop.cashToCollectDZD > 0 ? (
                          <span className="font-extrabold text-xs text-[#D9943B] block">
                            {stop.cashToCollectDZD} DZD
                          </span>
                        ) : (
                          <span className="text-[10px] text-zinc-500 block">Enlèvement</span>
                        )}
                        <div className="mt-0.5">
                          {isCompleted ? (
                            <span className="text-[10px] text-emerald-400 font-bold block">
                              ✓ {stop.completedAt || 'Fait'}
                            </span>
                          ) : (
                            <>
                              <span className="text-[11px] font-mono font-black text-white flex items-center justify-end gap-1">
                                <Clock size={10} className="text-[#D9943B]" />
                                <span>{stopETA?.estimatedArrivalClock || `+${stop.estimatedArrivalMin} min`}</span>
                              </span>
                              {stopETA && (
                                <span className="text-[9px] text-zinc-400 block">
                                  dans {stopETA.relativeMinutesFromNow} min
                                </span>
                              )}
                            </>
                          )}
                        </div>
                      </div>
                    </div>

                    {/* Proximity Corridor Inter-Stop Indicator */}
                    {sIdx > 0 && !isPickup && (
                      <div className="text-[10px] text-emerald-400/90 font-medium pl-8 mt-1.5 flex items-center gap-1">
                        <ArrowRight size={10} />
                        <span>
                          Enchaînement direct dans le même secteur (~{activeBatch.maxRadiusBetweenDropoffsMeters}m d'écart)
                        </span>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* CONSOLIDATED BATCH CASH REGISTER SUMMARY */}
        {activeBatch && (
          <div className="bg-[#1C1E23] border border-white/10 rounded-2xl p-4 shadow-lg space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-white flex items-center gap-2">
                <Coins size={16} className="text-[#D9943B]" />
                <span>Caisse Espèces de la Tournée (COD)</span>
              </span>
              <span className="text-[10px] text-zinc-400 font-semibold">Ahmed Rachedi</span>
            </div>

            <div className="grid grid-cols-2 gap-2 text-xs">
              <div className="bg-white/5 p-2.5 rounded-xl">
                <span className="text-zinc-400 text-[10px] block">Espèces perçues</span>
                <span className="font-extrabold text-base text-emerald-400">
                  {activeBatch.totalCashCollectedDZD} DZD
                </span>
                <span className="text-[9px] text-zinc-400 block">sur {activeBatch.totalCashToCollectDZD} DZD attendus</span>
              </div>

              <div className="bg-white/5 p-2.5 rounded-xl">
                <span className="text-zinc-400 text-[10px] block">Rémunération Net Livreur</span>
                <span className="font-extrabold text-base text-[#D9943B]">
                  +{activeBatch.totalCourierPayoutDZD} DZD
                </span>
                <span className="text-[9px] text-[#00B578] block font-bold">100% Zéro Commission</span>
              </div>
            </div>
          </div>
        )}

        {/* SELECTED STOP DETAIL MODAL (WITH PRECISE DYNAMIC ETA BREAKDOWN) */}
        {selectedStopDetail && (
          <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm flex items-end sm:items-center justify-center p-4">
            <div className="bg-[#1C1E23] border border-white/20 rounded-3xl w-full max-w-md overflow-hidden shadow-2xl animate-in slide-in-from-bottom duration-200">
              {/* Header */}
              <div className="bg-[#242830] px-4 py-3.5 border-b border-white/10 flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div
                    className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-black shrink-0 ${
                      selectedStopDetail.status === 'COMPLETED'
                        ? 'bg-zinc-700 text-zinc-300'
                        : selectedStopDetail.type === 'PICKUP'
                        ? 'bg-[#D9943B] text-[#071E26]'
                        : 'bg-[#00B578] text-white'
                    }`}
                  >
                    {selectedStopDetail.status === 'COMPLETED' ? '✓' : selectedStopDetail.stopNumber}
                  </div>
                  <div>
                    <h3 className="font-extrabold text-white text-sm">
                      {selectedStopDetail.roleLabel} • {selectedStopDetail.targetName}
                    </h3>
                    <span className="text-[10px] text-zinc-400">
                      Arrêt #{selectedStopDetail.stopNumber} sur {activeBatch?.stops.length || 0}
                    </span>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={() => setSelectedStopDetail(null)}
                  className="w-8 h-8 rounded-full bg-white/10 hover:bg-white/20 text-zinc-300 hover:text-white flex items-center justify-center transition-colors cursor-pointer"
                >
                  <X size={16} />
                </button>
              </div>

              {/* Body */}
              <div className="p-4 space-y-3.5 max-h-[75vh] overflow-y-auto">
                {/* Dynamic ETA Breakdown Box */}
                {(() => {
                  const stopEta = cumulativeETA?.stopsETA.find((s) => s.stopId === selectedStopDetail.id);
                  return (
                    <div className="bg-black/30 border border-white/10 rounded-2xl p-3.5 space-y-2.5">
                      <div className="flex items-center justify-between text-xs">
                        <span className="font-extrabold text-white flex items-center gap-1.5">
                          <Activity size={14} className="text-[#D9943B]" />
                          <span>Calcul ETA & Décalage Trafic</span>
                        </span>
                        <span className="text-[10px] text-emerald-400 font-mono font-bold">
                          {selectedStopDetail.status === 'COMPLETED'
                            ? 'Effectué'
                            : stopEta
                            ? `Prévu à ${stopEta.estimatedArrivalClock}`
                            : `+${selectedStopDetail.estimatedArrivalMin} min`}
                        </span>
                      </div>

                      <div className="grid grid-cols-2 gap-2 text-xs">
                        <div className="bg-white/5 p-2 rounded-xl">
                          <span className="text-[10px] text-zinc-400 block">Distance Cumulée</span>
                          <span className="font-mono font-extrabold text-white">
                            {stopEta ? `${(stopEta.cumulativeDistanceMeters / 1000).toFixed(2)} km` : '-'}
                          </span>
                          <span className="text-[9px] text-zinc-400 block">depuis départ livreur</span>
                        </div>

                        <div className="bg-white/5 p-2 rounded-xl">
                          <span className="text-[10px] text-zinc-400 block">Étape Directe</span>
                          <span className="font-mono font-extrabold text-emerald-400">
                            {stopEta ? `+${stopEta.segmentDistanceMeters} m` : '-'}
                          </span>
                          <span className="text-[9px] text-zinc-400 block">depuis arrêt précédent</span>
                        </div>
                      </div>

                      {stopEta && stopEta.trafficOffsetSeconds > 0 && selectedStopDetail.status !== 'COMPLETED' && (
                        <div className="flex items-center justify-between text-[11px] bg-amber-500/10 border border-amber-500/20 px-2.5 py-1.5 rounded-xl text-amber-300">
                          <span className="flex items-center gap-1">
                            <Car size={12} />
                            <span>Décalage trafic injecté :</span>
                          </span>
                          <span className="font-mono font-bold">
                            +{Math.round(stopEta.trafficOffsetSeconds / 60)} min ({cumulativeETA?.traffic.label})
                          </span>
                        </div>
                      )}
                    </div>
                  );
                })()}

                {/* Address & Instructions */}
                <div className="bg-white/5 border border-white/10 rounded-2xl p-3.5 space-y-2 text-xs">
                  <div className="flex items-start gap-2">
                    <MapPin size={15} className="text-[#D9943B] shrink-0 mt-0.5" />
                    <div>
                      <span className="font-bold text-white block">{selectedStopDetail.address}</span>
                      {selectedStopDetail.landmark && (
                        <span className="text-amber-300 text-[11px] block mt-0.5">
                          Repère : {selectedStopDetail.landmark}
                        </span>
                      )}
                    </div>
                  </div>

                  {selectedStopDetail.specialInstructions && (
                    <div className="pt-2 border-t border-white/5 text-[11px] text-zinc-300">
                      <span className="text-zinc-400 block font-semibold text-[10px] uppercase">Instructions :</span>
                      <span>{selectedStopDetail.specialInstructions}</span>
                    </div>
                  )}
                </div>

                {/* Items and COD */}
                <div className="grid grid-cols-2 gap-2 text-xs">
                  <div className="bg-white/5 border border-white/10 rounded-2xl p-3">
                    <span className="text-zinc-400 text-[10px] block font-bold uppercase">Contenu</span>
                    <span className="font-bold text-white text-xs block mt-0.5 truncate">
                      {selectedStopDetail.itemsSummary}
                    </span>
                    <span className="text-[9px] text-zinc-400 block">{selectedStopDetail.itemCount} article(s)</span>
                  </div>

                  <div className="bg-white/5 border border-white/10 rounded-2xl p-3">
                    <span className="text-zinc-400 text-[10px] block font-bold uppercase">Espèces COD</span>
                    <span className="font-mono font-extrabold text-[#D9943B] text-sm block mt-0.5">
                      {selectedStopDetail.cashToCollectDZD > 0
                        ? `${selectedStopDetail.cashToCollectDZD} DZD`
                        : 'Déjà payé en ligne'}
                    </span>
                    <span className="text-[9px] text-zinc-400 block">À percevoir au client</span>
                  </div>
                </div>

                {/* Contact phone action */}
                <div className="flex items-center justify-between bg-black/40 p-3 rounded-2xl border border-white/10">
                  <div className="flex items-center gap-2">
                    <User size={15} className="text-zinc-400" />
                    <div>
                      <span className="text-white text-xs font-bold block">{selectedStopDetail.targetName}</span>
                      <span className="text-zinc-400 text-[10px]">{selectedStopDetail.contactPhone}</span>
                    </div>
                  </div>

                  <a
                    href={`tel:${selectedStopDetail.contactPhone}`}
                    className="px-3 py-1.5 bg-emerald-500 hover:bg-emerald-400 text-zinc-950 font-black text-xs rounded-xl flex items-center gap-1.5 transition-colors"
                  >
                    <Phone size={12} />
                    <span>Appeler</span>
                  </a>
                </div>

                <button
                  type="button"
                  onClick={() => setSelectedStopDetail(null)}
                  className="w-full py-2.5 bg-white/10 hover:bg-white/20 text-white font-bold text-xs rounded-xl transition-colors cursor-pointer"
                >
                  Fermer
                </button>
              </div>
            </div>
          </div>
        )}

        {/* TOAST ALERT */}
        {toastMessage && (
          <div className="fixed bottom-16 inset-x-4 max-w-sm mx-auto z-50 bg-[#D9943B] text-[#071E26] px-4 py-3 rounded-2xl shadow-2xl flex items-center gap-2.5 text-xs font-black animate-in fade-in slide-in-from-bottom duration-200">
            <Sparkles size={16} className="shrink-0" />
            <span>{toastMessage}</span>
          </div>
        )}
      </main>
    </div>
  );
};
